# fly.toml app configuration file generated for my-chat-bot-discord-relay on 2026-04-22T17:17:40+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-chat-bot-discord-relay'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
